{{- if .Values.persistence.createPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.names.n8nPvc }}
  namespace: {{ include "n8n.namespace" . | quote }}
  labels:
    io.kompose.service: n8n-data
    {{- include "n8n.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  volumeMode: {{ .Values.persistence.volumeMode }}
{{- end }}
