{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.names.secret }}
  namespace: {{ include "n8n.namespace" . | quote }}
  labels:
    io.kompose.service: n8n
    {{- include "n8n.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.dbPasswordKey }}: {{ .Values.secret.dbPassword | quote }}
  {{ .Values.secret.postgresPasswordKey }}: {{ .Values.secret.postgresPassword | quote }}
  {{ .Values.secret.postgresNonRootPasswordKey }}: {{ .Values.secret.postgresNonRootPassword | quote }}
{{- end }}
