apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.n8nService }}
  namespace: {{ include "n8n.namespace" . | quote }}
  labels:
    io.kompose.service: n8n
    {{- include "n8n.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.n8n.type }}
  selector:
    io.kompose.service: n8n
  ports:
    - name: {{ .Values.service.n8n.name }}
      port: {{ .Values.service.n8n.port }}
      protocol: TCP
      targetPort: {{ .Values.service.n8n.targetPort }}
