{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.names.secret }}
  namespace: {{ include "guacamole.namespace" . | quote }}
  labels:
    {{- include "guacamole.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.dbPasswordKey }}: {{ .Values.secret.dbPassword | quote }}
{{- end }}
