name: Publish Helm Chart Repo

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"
      - "repo/**"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package chart
        run: |
          helm package charts/guacamole -d repo

      - name: Update index
        run: |
          helm repo index repo --url https://windoc.github.io/helm-charts

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: repo
          publish_branch: gh-pages
